### PR TITLE
Update frontend.txt

### PR DESCRIPTION
**Pull request by Sarabudheen**
Hi Bharath Mattew I have uploaded my first version of my onlinq quiz portal project files.Please verify and review it.Let me know if anything need to be change.

### CODE REVIEW

**Comment by BarathMatthew** [comment]
Hi sara I have verified your front end there are some unused methods in user.service.ts file and in admin.component you have commented unused code update both and let me know

**Comment by Sarabudheen** [comment]
Hi Matthew I have updated the front end as per your suggestion can you verify it.

**Review by BarathMatthew — CHANGES_REQUESTED** [review]
I have verified your front end it fine .In the back-end add comments to every methods in the user and question controller

**Comment by Sarabudheen** [comment]
I have updated the changes in back end files.Please review it and kindly update the status.

**Review by BarathMatthew — APPROVED** [review]
Hi sara everything is fine thank you

**Pull request merged**
